[2024-04-29T13:50:07.790+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T13:50:07.826+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_csv_to_azure_blob.export_csv manual__2024-04-29T13:45:02.825110+00:00 [queued]>
[2024-04-29T13:50:07.835+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_csv_to_azure_blob.export_csv manual__2024-04-29T13:45:02.825110+00:00 [queued]>
[2024-04-29T13:50:07.835+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-29T13:50:07.851+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): export_csv> on 2024-04-29 13:45:02.825110+00:00
[2024-04-29T13:50:07.860+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'export_csv_to_azure_blob', 'export_csv', 'manual__2024-04-29T13:45:02.825110+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/export_csv.py', '--cfg-path', '/tmp/tmpd9ja23er']
[2024-04-29T13:50:07.863+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask export_csv
[2024-04-29T13:50:07.864+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=443) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T13:50:07.865+0000] {standard_task_runner.py:63} INFO - Started process 445 to run task
[2024-04-29T13:50:07.914+0000] {task_command.py:426} INFO - Running <TaskInstance: export_csv_to_azure_blob.export_csv manual__2024-04-29T13:45:02.825110+00:00 [running]> on host 270d16ab0cac
[2024-04-29T13:50:08.013+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='export_csv_to_azure_blob' AIRFLOW_CTX_TASK_ID='export_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T13:45:02.825110+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T13:45:02.825110+00:00'
[2024-04-29T13:50:08.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T13:50:08.032+0000] {logging_mixin.py:188} INFO - Uploading...
[2024-04-29T13:50:08.033+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T13:50:08.033+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/export_csv.py", line 20, in export_csv_to_azure_blob
    blob_container.upload_blob(blob_name, file, overwrite=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_container_client.py", line 1101, in upload_blob
    blob.upload_blob(
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py", line 758, in upload_blob
    options = self._upload_blob_options(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py", line 404, in _upload_blob_options
    raise TypeError(f"Unsupported data type: {type(data)}")
TypeError: Unsupported data type: <class 'int'>
[2024-04-29T13:50:08.047+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=export_csv_to_azure_blob, task_id=export_csv, execution_date=20240429T134502, start_date=20240429T135007, end_date=20240429T135008
[2024-04-29T13:50:08.061+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task export_csv (Unsupported data type: <class 'int'>; 445)
[2024-04-29T13:50:08.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T13:50:08.106+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T13:50:08.112+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
